drop table user if exists;
create table user (
  id int generated by default as identity,
  create_time varchar(20) ,
  name varchar(20),
  password varchar(36),
  phone varchar(20),
  nick_name varchar(20),
  primary key (id)
);

drop table employee if exists;
create table employee (
  id int generated by default as identity,
  name varchar(20),
  dept_id int,
  primary key (id)
);

drop table dept if exists;
create table dept (
  id int generated by default as identity,
  name varchar(20),
  primary key (id)
);

